server:
  port: 8080
front-server:
    port: ${DEV_CLIENT_URL}

spring:
  config:
    import:
        - classpath:keys.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    url: ${LOCAL_DB_URL}
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false # true, false
        show_sql: false # true, false
    hibernate:
      ddl-auto: none # create, create-drop, update, validate, none


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    doc-expansion: none