spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    url: ${LOCAL_DB_URL}
  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      password: ${LOCAL_REDIS_PASSWORD}
      database: ${LOCAL_REDIS_DATABASE}
      port: 6379
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
url:
  front: http://localhost:3000
  base: http://localhost:8080
  path:
    login: login
    signup: signup
server:
  port: 8080