version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: dockers/app.Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../src/main/resources/envs.env
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - db

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_DATABASE: verdict
      MYSQL_USER: verdict
      MYSQL_PASSWORD: sa
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  redis_data: